channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - ld_impl_linux-64=2.40
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgomp=12.2.0
  - libnsl=2.0.0
  - libsqlite=3.40.0
  - libuuid=2.38.1
  - libzlib=1.2.13
  - ncurses=6.3
  - openssl=3.1.0
  - pip=23.1.2
  - python=3.10.10
  - readline=8.2
  - setuptools=67.7.2
  - tk=8.6.12
  - wheel=0.40.0
  - xz=5.2.6
  - pip:
    - absl-py==1.4.0
    - aiofiles==22.1.0
    - aiosqlite==0.19.0
    - anndata==0.9.1
    - anyio==3.6.2
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - astroid==2.15.4
    - asttokens==2.2.1
    - astunparse==1.6.3
    - attrs==23.1.0
    - autoflake==2.1.1
    - babel==2.12.1
    - backcall==0.2.0
    - beautifulsoup4==4.12.2
    - black==23.3.0
    - bleach==6.0.0
    - cachetools==5.3.0
    - certifi==2022.12.7
    - cffi==1.15.1
    - charset-normalizer==3.1.0
    - click==8.1.3
    - comm==0.1.3
    - contourpy==1.0.7
    - cycler==0.11.0
    - debugpy==1.6.7
    - decorator==5.1.1
    - defusedxml==0.7.1
    - dill==0.3.6
    - executing==1.2.0
    - fastjsonschema==2.16.3
    - flatbuffers==23.3.3
    - fonttools==4.39.3
    - fqdn==1.5.1
    - gast==0.4.0
    - google-auth==2.17.3
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.54.0
    - h5py==3.8.0
    - idna==3.4
    - igraph==0.10.4
    - ipykernel==6.22.0
    - ipython==8.13.1
    - ipython-genutils==0.2.0
    - isoduration==20.11.0
    - isort==5.12.0
    - ivae-scorer==1.0.0
    - jedi==0.18.2
    - jinja2==3.1.2
    - joblib==1.2.0
    - json5==0.9.11
    - jsonpointer==2.3
    - jsonschema==4.17.3
    - jupyter-client==8.2.0
    - jupyter-core==5.3.0
    - jupyter-events==0.6.3
    - jupyter-server==2.5.0
    - jupyter-server-fileid==0.9.0
    - jupyter-server-terminals==0.4.4
    - jupyter-server-ydoc==0.8.0
    - jupyter-ydoc==0.2.4
    - jupyterlab==3.6.3
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.22.1
    - keras==2.10.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.4
    - lazy-object-proxy==1.9.0
    - leidenalg==0.9.1
    - libclang==16.0.0
    - llvmlite==0.39.1
    - markdown==3.4.3
    - markupsafe==2.1.2
    - matplotlib==3.7.1
    - matplotlib-inline==0.1.6
    - mccabe==0.7.0
    - mistune==2.0.5
    - mypy-extensions==1.0.0
    - natsort==8.3.1
    - nbclassic==0.5.6
    - nbclient==0.7.4
    - nbconvert==7.3.1
    - nbformat==5.8.0
    - nest-asyncio==1.5.6
    - networkx==3.1
    - notebook==6.5.4
    - notebook-shim==0.2.3
    - numba==0.56.4
    - numpy==1.23.5
    - oauthlib==3.2.2
    - opt-einsum==3.3.0
    - packaging==23.1
    - pandas==2.0.1
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathspec==0.11.1
    - patsy==0.5.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.5.0
    - platformdirs==3.5.0
    - prometheus-client==0.16.0
    - prompt-toolkit==3.0.38
    - protobuf==3.19.6
    - psutil==5.9.5
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pycparser==2.21
    - pyflakes==3.0.1
    - pygments==2.15.1
    - pylint==2.17.3
    - pynndescent==0.5.10
    - pyparsing==3.0.9
    - pyrsistent==0.19.3
    - python-dateutil==2.8.2
    - python-dotenv==1.0.0
    - python-igraph==0.10.4
    - python-json-logger==2.0.7
    - pytz==2023.3
    - pyyaml==6.0
    - pyzmq==25.0.2
    - requests==2.29.0
    - requests-oauthlib==1.3.1
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rsa==4.9
    - scanpy==1.9.3
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - seaborn==0.12.2
    - send2trash==1.8.2
    - session-info==1.0.0
    - six==1.16.0
    - sniffio==1.3.0
    - soupsieve==2.4.1
    - stack-data==0.6.2
    - statsmodels==0.14.0rc0
    - stdlib-list==0.8.0
    - tensorboard==2.10.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow-estimator==2.10.0
    - tensorflow-gpu==2.10.0
    - tensorflow-io-gcs-filesystem==0.32.0
    - termcolor==2.3.0
    - terminado==0.17.1
    - texttable==1.6.7
    - threadpoolctl==3.1.0
    - tinycss2==1.2.1
    - tomli==2.0.1
    - tomlkit==0.11.8
    - tornado==6.3.1
    - tqdm==4.65.0
    - traitlets==5.9.0
    - typing-extensions==4.5.0
    - tzdata==2023.3
    - umap-learn==0.5.3
    - uri-template==1.2.0
    - urllib3==1.26.15
    - wcwidth==0.2.6
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.5.1
    - werkzeug==2.3.2
    - wrapt==1.15.0
    - y-py==0.5.9
    - ypy-websocket==0.8.2
