channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=1.4.0
  - aiofiles=22.1.0
  - aiohttp=3.7.4.post0
  - aiosqlite=0.19.0
  - anndata=0.9.1
  - anyio=3.6.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arpack=3.7.0
  - astroid=2.15.4
  - asttokens=2.2.1
  - astunparse=1.6.3
  - async-timeout=3.0.1
  - attrs=22.2.0
  - autoflake=1.7.5
  - babel=2.12.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.12.2
  - black=23.3.0
  - black-jupyter=23.3.0
  - bleach=6.0.0
  - blinker=1.6.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.3.0
  - certifi=2022.12.7
  - cffi=1.15.1
  - chardet=4.0.0
  - charset-normalizer=3.1.0
  - click=8.1.3
  - colorama=0.4.6
  - comm=0.1.3
  - contourpy=1.0.7
  - cryptography=39.0.0
  - cuda-version=11.8
  - cudatoolkit=11.8.0
  - cudnn=8.8.0.121
  - cycler=0.11.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.6
  - entrypoints=0.4
  - executing=1.2.0
  - flatbuffers=2.0.8
  - flit-core=3.8.0
  - fonttools=4.39.3
  - freetype=2.12.1
  - gast=0.4.0
  - giflib=5.2.1
  - glpk=5.0
  - gmp=6.2.1
  - google-auth=2.17.3
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - grpc-cpp=1.47.1
  - grpcio=1.47.1
  - h5py=3.8.0
  - hdf5=1.14.0
  - icu=70.1
  - idna=3.4
  - igraph=0.10.3
  - importlib-metadata=6.6.0
  - importlib_metadata=6.6.0
  - importlib_resources=5.12.0
  - ipykernel=6.22.0
  - ipython=8.12.0
  - ipython_genutils=0.2.0
  - isort=5.12.0
  - jedi=0.18.2
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - json5=0.9.5
  - jsonschema=4.17.3
  - jupyter_client=8.2.0
  - jupyter_core=5.3.0
  - jupyter_events=0.6.3
  - jupyter_server=2.5.0
  - jupyter_server_fileid=0.9.0
  - jupyter_server_terminals=0.4.4
  - jupyter_server_ydoc=0.8.0
  - jupyter_ydoc=0.2.3
  - jupyterlab=3.6.3
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.22.1
  - keras=2.10.0
  - keras-preprocessing=1.1.2
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lazy-object-proxy=1.9.0
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - leidenalg=0.9.1
  - lerc=4.0.0
  - libabseil=20220623.0
  - libaec=1.0.6
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.87.0
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libgomp=12.2.0
  - libhwloc=2.9.1
  - libiconv=1.17
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libnghttp2=1.51.0
  - libnsl=2.0.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libprotobuf=3.21.12
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libtiff=4.5.0
  - libuuid=2.38.1
  - libwebp-base=1.3.0
  - libxcb=1.13
  - libxml2=2.10.3
  - libzlib=1.2.13
  - llvmlite=0.39.1
  - markdown=3.4.3
  - markupsafe=2.1.2
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - metis=5.1.0
  - mistune=2.0.5
  - mpfr=4.2.0
  - multidict=6.0.4
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - natsort=8.3.1
  - nbclassic=0.5.6
  - nbclient=0.7.4
  - nbconvert=7.3.1
  - nbconvert-core=7.3.1
  - nbconvert-pandoc=7.3.1
  - nbformat=5.8.0
  - nccl=2.15.5.1
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - networkx=3.1
  - notebook=6.5.4
  - notebook-shim=0.2.3
  - numba=0.56.4
  - numpy=1.23.5
  - oauthlib=3.2.2
  - openjpeg=2.5.0
  - openssl=1.1.1t
  - opt_einsum=3.3.0
  - packaging=23.1
  - pandas=2.0.1
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pathspec=0.11.1
  - patsy=0.5.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.1.2
  - platformdirs=3.5.0
  - pooch=1.7.0
  - prometheus_client=0.16.0
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - protobuf=4.21.12
  - psutil=5.9.5
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pyflakes=3.0.1
  - pygments=2.15.1
  - pyjwt=2.6.0
  - pylint=2.17.3
  - pynndescent=0.5.10
  - pyopenssl=23.1.1
  - pyparsing=3.0.9
  - pyrsistent=0.19.3
  - pysocks=1.7.1
  - python=3.10.8
  - python-dateutil=2.8.2
  - python-dotenv=1.0.0
  - python-fastjsonschema=2.16.3
  - python-flatbuffers=23.1.21
  - python-igraph=0.10.3
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytz=2023.3
  - pyu2f=0.1.5
  - pyyaml=6.0
  - pyzmq=25.0.2
  - re2=2022.06.01
  - readline=8.2
  - requests=2.29.0
  - requests-oauthlib=1.3.1
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rsa=4.9
  - scanpy=1.9.3
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - seaborn=0.12.2
  - seaborn-base=0.12.2
  - send2trash=1.8.2
  - session-info=1.0.0
  - setuptools=67.7.2
  - six=1.16.0
  - snappy=1.1.10
  - sniffio=1.3.0
  - soupsieve=2.3.2.post1
  - stack_data=0.6.2
  - statsmodels=0.13.5
  - stdlib-list=0.8.0
  - suitesparse=5.10.1
  - tbb=2021.9.0
  - tensorboard=2.10.1
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.10.0
  - tensorflow-base=2.10.0
  - tensorflow-estimator=2.10.0
  - termcolor=2.3.0
  - terminado=0.17.1
  - texttable=1.6.7
  - threadpoolctl=3.1.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - tokenize-rt=5.0.0
  - tomli=2.0.1
  - tomlkit=0.11.7
  - tornado=6.3
  - tqdm=4.65.0
  - traitlets=5.9.0
  - typing=3.10.0.0
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - tzdata=2023c
  - umap-learn=0.5.3
  - unicodedata2=15.0.0
  - urllib3=1.26.15
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - websocket-client=1.5.1
  - werkzeug=2.3.1
  - wheel=0.40.0
  - wrapt=1.15.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - y-py=0.5.9
  - yaml=0.2.5
  - yarl=1.9.1
  - ypy-websocket=0.8.2
  - zeromq=4.3.4
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.2
